'use strict';

function checkError(catchedError)
{
    let errorCause = catchedError.cause;
    
}